# Generated by Django 6.1.1 on 2026-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_DB',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=10)),
                ('issue', models.TextField()),
                ('payment_method', models.CharField()),
                ('date_of_arrival', models.DateField()),
                ('exp_date_of_departure', models.DateField()),
            ],
        ),
    ]
